import os
import argparse
import math

# Simple OBJ writer for basic primitives (cube for now)
# Usage:
#   python render/make_mesh.py --shape cube --size 2.0 --out render/assets/demo_cube.obj
# This script is pure Python and does not require Blender.


def write_obj(vertices, faces, out_path):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# simple OBJ generated by make_mesh.py\n")
        for v in vertices:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")
        # single default uv/normal not required for basic geometry
        for face in faces:
            # OBJ is 1-indexed
            a, b, c, d = face
            f.write(f"f {a} {b} {c} {d}\n")
    print(f"[MAKE_MESH] Wrote OBJ: {out_path} (v={len(vertices)} f={len(faces)})")


def make_cube(size=2.0):
    s = size * 0.5
    # 8 vertices of a cube
    vertices = [
        (-s, -s, -s), ( s, -s, -s), ( s,  s, -s), (-s,  s, -s),
        (-s, -s,  s), ( s, -s,  s), ( s,  s,  s), (-s,  s,  s),
    ]
    # 6 quad faces (OBJ supports quads)
    faces = [
        (1, 2, 3, 4),  # bottom
        (5, 6, 7, 8),  # top
        (1, 5, 8, 4),  # left
        (2, 6, 7, 3),  # right
        (1, 2, 6, 5),  # front
        (4, 3, 7, 8),  # back
    ]
    return vertices, faces
def make_ball(size=2.0, subdivisions=16):
    """
    Create a spherified-cube sphere as a quad-mesh.
    Returns (vertices, faces) where faces are quads (4-tuples of 1-based indices).
    """
    r = float(size) * 0.5
    n = max(1, int(subdivisions))

    vertices = []
    faces = []
    vert_map = {}

    def add_vertex(v):
        # Deduplicate by rounded coordinates to share seam vertices
        key = (round(v[0], 8), round(v[1], 8), round(v[2], 8))
        idx = vert_map.get(key)
        if idx is None:
            vertices.append(v)
            idx = len(vertices)  # 1-based index for OBJ
            vert_map[key] = idx
        return idx

    # face parameterization functions (u,v in [-1,1])
    face_funcs = [
        lambda u, v: ( 1.0, u, v),  # +X
        lambda u, v: (-1.0, u, -v), # -X
        lambda u, v: (u,  1.0, v),  # +Y
        lambda u, v: (u, -1.0, -v), # -Y
        lambda u, v: (u, v,  1.0),  # +Z
        lambda u, v: (-u, v, -1.0), # -Z
    ]

    for face_func in face_funcs:
        # build grid of indices for this face
        grid = [[0 for _ in range(n + 1)] for _ in range(n + 1)]
        for i in range(n + 1):
            u = -1.0 + 2.0 * i / n
            for j in range(n + 1):
                v = -1.0 + 2.0 * j / n
                x, y, z = face_func(u, v)
                # project cube point onto sphere
                length = math.sqrt(x * x + y * y + z * z)
                vx = (x / length) * r
                vy = (y / length) * r
                vz = (z / length) * r
                grid[i][j] = add_vertex((vx, vy, vz))

        # create quads for this face
        for i in range(n):
            for j in range(n):
                v00 = grid[i][j]
                v10 = grid[i + 1][j]
                v11 = grid[i + 1][j + 1]
                v01 = grid[i][j + 1]
                faces.append((v00, v10, v11, v01))

    return vertices, faces


def main():
    parser = argparse.ArgumentParser(description="Generate a simple OBJ mesh")
    parser.add_argument("--shape", default="cube", choices=["cube", "ball"], help="Shape type")
    parser.add_argument("--size", type=float, default=2.0, help="Overall size")
    parser.add_argument("--out", required=True, help="Output OBJ path")
    args = parser.parse_args()

    if args.shape == "cube":
        v, f = make_cube(args.size)
    elif args.shape == "ball":
        v, f = make_ball(args.size)
    else:
        raise ValueError("Unsupported shape")

    write_obj(v, f, args.out)


if __name__ == "__main__":
    main()
